### PR TITLE
Update itIT.lua

### PR DESCRIPTION
**Pull request by LucaQapla**

### CODE REVIEW

**Comment by funkydude** [comment]
Can you also translate https://github.com/funkydude/BFAInvasionTimer/blob/master/Options/Locales/itIT.lua ?

**Comment by funkydude** [comment]
@LucaQapla Can you please follow up with whether or not you plan on translating the options to Italian?

**Comment by seipher91** [comment]
@funkydude i traslated the options to Italian. You can marge it

**Comment by funkydude** [comment]
@seipher91 I see the changes you made on your own repository. But you have not submitted them to my repository as a pull request. Can you please do that?

**Comment by seipher91** [comment]
Done ;)

**Pull request merged**
